name: CI
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        run: hugo -t hello-friend-ng

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: pagidas/pagidas.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: pagidas
          user_email: pagakrivos@gmail.com
          publish_branch: main
        #   cname: example.com
