name: Build hugo project and push changes to git submodule

on:
  push:
    branches: [ master ]

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1

    - name: Build and Deploy
      uses: victoriadrake/hugo-latest-cd@master

#    - name: Setup Hugo
#      uses: peaceiris/actions-hugo@v2
#      with:
#        hugo-version: '0.79.1'
#
#    - name: Build
#      run: hugo --minify
#
#    - name: Deploy
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./public